config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  # get 'home/index'
  root 'home#index'
  get 'home/about'

  post "/" => 'home#index'

  # devise_for :users

devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          has_many :stocks     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @api = StockQuote::Stock.new(api_key: "pk_8d70766670d24742bb22d53f76baa317")
  #   if params[:ticker] == ""
  #     @nothing = "Please Enter a Symbol"
  #  elsif params[:ticker]
  #    begin
  #      @stock = StockQuote::Stock.quote(params[:ticker])
  #    rescue RuntimeError
  #          @error = "Hey! That stock Symbol Doesn't Exist"
  #    end  
  #  end

  end

  def about
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:edit,:update,:destroy]
  before_action :authenticate_user!

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @ticker = current_user.stocks.find_by(id: params[:id])
    redirect_to stocks_path, notice: "Not Authorized to edit this stock" if @ticker.nil?
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<% flash.each do |name, msg|%>
        <div class="alert alert-warning alert-dismissable" role="alert">
            <button class="close" data-dismiss="alert">
                <small><sup>x</sup></small>
            </button> 
            <%= content_tag(:div, msg)%>   

        </div>

<% end %>

app/views/home/_footer.html.erb
<br/><br/><br/><br/><br/><br/>
<center>CopyRight(c) Gladdy </center>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Stocking', root_path, class:"navbar-brand"%>
  <%# <a class="navbar-brand" href="#">Stocking</a> %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'About Me', home_about_path, class:"nav-link" %>
        <%# <a class="nav-link" href="#">Link</a> %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Show Stocks', stocks_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add Stocks', new_stock_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Login', new_user_session_path, class:"nav-link" %>
        </li>
      <%end%>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-dark my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About</h1>
<p>Hello This is Gladdy Making my first Rails App</p>

app/views/home/index.html.erb
<h1>Stocking</h1>
<p>Track All Your Stock Options on this WebApplication</p>
<%# <%= turbo_frame_tag "post" do %> 
    <%= form_tag root_path, :method => 'POST' do %>
        <%= text_field_tag 'ticker', nil, placeholder: "Enter Ticker Symbol", size: 50 %>
        <%= submit_tag 'Lookup' %>
    <% end %>   

<% if @stock %> 
    Name: <%= @stock.company_name %><br/>
    Latest price $<%= @stock.latest_price%><br/>
    52 Weeks High $<%= @stock.week52_high%><br/>
    53 Week Low $<%= @stock.week52_low%><br/>
<% elsif @nothing %>
    <%= @nothing%>
<% end %>    

<% if @error %>
    <%= @error %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stock Market WebApplication</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "home/navbar" %>
    <br/>
    <div class="container">
        <%= render 'home/flash'%>
        
      <br/>  
      <%= yield %>
    </div>
    <%= render "home/footer" %>
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock) do |form| %>
  <% if stock.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ticker, style: "display: block" %>
    <%= form.text_field :ticker %>
  </div>

  <div>
    <% form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, id: :stock_user_id, value: current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/_stock.html.erb
<div id="<%= dom_id stock %>">
  <p>
    <strong>Ticker:</strong>
    <%= stock.ticker %>
  </p>

  <%# <p>
    <strong>User:</strong>
    <% stock.user_id %>
  <%# </p> %> 

</div>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Show this stock", @stock %> |
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/index.html.erb
<h1>Stocks</h1>
<div id="stocks">
  <% @stocks.each do |stock| %>
    <% if stock.user_id == current_user.id %>
      <%if stock.ticker == ""%>
        <%=@ticker.company_name = "N/A"%>
        <%=@ticker.symbol = "N/A"%>
        <%=@ticker.latest_price = "N/A"%>
      <%elsif stock.ticker %>
        <%begin %>
          <%@ticker = StockQuote::Stock.quote(stock.ticker) %>
          <%rescue RuntimeError %>
          <%=@ticker.company_name = "N/A"%>
          <%=@ticker.symbol = "N/A"%>
          <%=@ticker.latest_price = "N/A"%>
        <%end%>
      <%end%>
      <%= render stock %>
      <tr>
        <td></td>
        <td><%= @ticker.company_name  %></td>
        <td><%= @ticker.symbol  %></td>
        <td><%= @ticker.latest_price%></td>
      </tr>
      <p>
        <%= link_to "Show this stock", stock %>
      </p>
    <%end%>
  <%end%>
</div>
<%= link_to "New stock", new_stock_path %>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/show.html.erb
<%= render @stock %>

<div>
  <%= link_to "Edit this stock", edit_stock_path(@stock) %> |
  <%= link_to "Back to stocks", stocks_path %>

  <%= button_to "Destroy this stock", @stock, method: :delete %>
</div>